// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/employee.proto

package employeeDB

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeDatabaseCrudClient is the client API for EmployeeDatabaseCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeDatabaseCrudClient interface {
	AddEmployee(ctx context.Context, in *NewEmployee, opts ...grpc.CallOption) (*Employee, error)
	GetEmployees(ctx context.Context, in *EmptyEmployeeRequest, opts ...grpc.CallOption) (*AllEmployees, error)
	UpdateRoleOfEmployee(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*Employee, error)
	DeleteEmployee(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*EmptyEmployeeResponse, error)
}

type employeeDatabaseCrudClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeDatabaseCrudClient(cc grpc.ClientConnInterface) EmployeeDatabaseCrudClient {
	return &employeeDatabaseCrudClient{cc}
}

func (c *employeeDatabaseCrudClient) AddEmployee(ctx context.Context, in *NewEmployee, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/employeeDB.EmployeeDatabaseCrud/AddEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) GetEmployees(ctx context.Context, in *EmptyEmployeeRequest, opts ...grpc.CallOption) (*AllEmployees, error) {
	out := new(AllEmployees)
	err := c.cc.Invoke(ctx, "/employeeDB.EmployeeDatabaseCrud/GetEmployees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) UpdateRoleOfEmployee(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/employeeDB.EmployeeDatabaseCrud/UpdateRoleOfEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) DeleteEmployee(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*EmptyEmployeeResponse, error) {
	out := new(EmptyEmployeeResponse)
	err := c.cc.Invoke(ctx, "/employeeDB.EmployeeDatabaseCrud/DeleteEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeDatabaseCrudServer is the server API for EmployeeDatabaseCrud service.
// All implementations must embed UnimplementedEmployeeDatabaseCrudServer
// for forward compatibility
type EmployeeDatabaseCrudServer interface {
	AddEmployee(context.Context, *NewEmployee) (*Employee, error)
	GetEmployees(context.Context, *EmptyEmployeeRequest) (*AllEmployees, error)
	UpdateRoleOfEmployee(context.Context, *Employee) (*Employee, error)
	DeleteEmployee(context.Context, *Employee) (*EmptyEmployeeResponse, error)
	mustEmbedUnimplementedEmployeeDatabaseCrudServer()
}

// UnimplementedEmployeeDatabaseCrudServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeDatabaseCrudServer struct {
}

func (UnimplementedEmployeeDatabaseCrudServer) AddEmployee(context.Context, *NewEmployee) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmployee not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) GetEmployees(context.Context, *EmptyEmployeeRequest) (*AllEmployees, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployees not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) UpdateRoleOfEmployee(context.Context, *Employee) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleOfEmployee not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) DeleteEmployee(context.Context, *Employee) (*EmptyEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmployee not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) mustEmbedUnimplementedEmployeeDatabaseCrudServer() {}

// UnsafeEmployeeDatabaseCrudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeDatabaseCrudServer will
// result in compilation errors.
type UnsafeEmployeeDatabaseCrudServer interface {
	mustEmbedUnimplementedEmployeeDatabaseCrudServer()
}

func RegisterEmployeeDatabaseCrudServer(s grpc.ServiceRegistrar, srv EmployeeDatabaseCrudServer) {
	s.RegisterService(&EmployeeDatabaseCrud_ServiceDesc, srv)
}

func _EmployeeDatabaseCrud_AddEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEmployee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).AddEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeDB.EmployeeDatabaseCrud/AddEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).AddEmployee(ctx, req.(*NewEmployee))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_GetEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).GetEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeDB.EmployeeDatabaseCrud/GetEmployees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).GetEmployees(ctx, req.(*EmptyEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_UpdateRoleOfEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Employee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).UpdateRoleOfEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeDB.EmployeeDatabaseCrud/UpdateRoleOfEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).UpdateRoleOfEmployee(ctx, req.(*Employee))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_DeleteEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Employee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).DeleteEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeDB.EmployeeDatabaseCrud/DeleteEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).DeleteEmployee(ctx, req.(*Employee))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeDatabaseCrud_ServiceDesc is the grpc.ServiceDesc for EmployeeDatabaseCrud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeDatabaseCrud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employeeDB.EmployeeDatabaseCrud",
	HandlerType: (*EmployeeDatabaseCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEmployee",
			Handler:    _EmployeeDatabaseCrud_AddEmployee_Handler,
		},
		{
			MethodName: "GetEmployees",
			Handler:    _EmployeeDatabaseCrud_GetEmployees_Handler,
		},
		{
			MethodName: "UpdateRoleOfEmployee",
			Handler:    _EmployeeDatabaseCrud_UpdateRoleOfEmployee_Handler,
		},
		{
			MethodName: "DeleteEmployee",
			Handler:    _EmployeeDatabaseCrud_DeleteEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/employee.proto",
}
