CREATE OR REPLACE FUNCTION CHECK_USERNAME()
RETURNS TRIGGER
AS $BODY$
BEGIN
IF LENGTH(NEW.NAME) < 6 THEN
    raise exception 'length cant be less than 5';
ELSE RETURN NEW;
END IF;
END;
$BODY$ LANGUAGE plpgsql;